In [1]:
#Standard Library Imports. 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import astropy
from astropy.io import fits

In [3]:
fits_image_filename = 'mangaHIall_dr3GOOD_rc_parameters_yyoon.fits'

In [5]:
astropy.io.fits.open('mangaHIall_dr3GOOD_rc_parameters_yyoon.fits')

FileNotFoundError: [Errno 2] No such file or directory: 'mangaHIall_dr3GOOD_rc_parameters_yyoon.fits'

In [ ]:
hdul = fits.open(fits_image_filename)

In [ ]:
hdul

In [8]:
hdul.info()

Filename: mangaHIall_dr3GOOD_rc_parameters_yyoon.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      16   (3460,)   uint8
  1  Joined        1 BinTableHDU     92   80R x 40C   [11A, D, D, D, D, D, D, D, D, 9A, D, D, E, 79A, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, I, I, I, D]

In [9]:
hdul.close()

In [10]:
with fits.open(fits_image_filename) as hdul:
    hdul.info()

Filename: mangaHIall_dr3GOOD_rc_parameters_yyoon.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      16   (3460,)   uint8
  1  Joined        1 BinTableHDU     92   80R x 40C   [11A, D, D, D, D, D, D, D, D, 9A, D, D, E, 79A, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, I, I, I, D]

In [11]:
with fits.open(fits_image_filename) as hdul:
    data = hdul[1].data
    data

In [12]:
len(data)

80

In [13]:
data

FITS_rec([('10213-9101', 122.36352  ,  4.3934918e+01, 207.03249 , 3.7470374 , -3.6288854e+00, -9.9420569e+00, 64.449786, 161.11613   , '1-44999',  9.91829618, 0.82632782,  6884.2   , 'AGBT17A_012_340',  846.18695, 1.7190437 , -999., 0.01947592, 10.329507 , 4.07699  , 0.15571973,  9.96224 ,  6874.3486,  4.78287  ,  343.6021 ,  333.9316 , 348.96988,  334.0506  , 335.87897 ,    7.5238743,   16.22993 ,   16.028118,  109.80094 ,  5.8300972e-01,  102.230255, -5.4048181e-01, 0, 0, 0, 0.),
          ('10214-1902', 121.98829  ,  3.4227327e+01,  26.348096, 0.4287873 ,  4.4978814e+00, -2.9142451e+00, 31.790592, 276.26228   , '1-153402',  9.48339614, 0.38640048,  6528.5   , 'AGBT19A_127_26',  766.1663 , 1.3827271 , -999., 0.01663199, 11.028398 , 2.062905 , 0.0925824 ,  9.623957,  6544.464 ,  7.5590158,  149.48021,  135.992  , 162.12325,  136.53485 , 141.10814 ,    7.851486 ,   13.094404,   13.859993,   40.737713,  4.5684454e-01,   20.681894, -1.8827482e-01, 0, 0, 0, 0.),
          ('10214-6101', 123.06182  ,  3.5157138e+01,  29.521736, 0.996485  ,  4.7203910e-01, -1.9741566e+01, 49.908095,  67.802374  , '1-153412',  9.36784772, 0.84843245,  5244.    , 'AGBT19A_127_26',  895.6127 , 1.3858749 , -999., 0.02025456, 13.614999 , 2.6843128, 0.10899388,  9.545134,  5234.6675,  9.250498 ,  241.73016,  203.83472, 243.13565,  228.7368  , 226.88501 ,    8.990848 ,    9.675129,   16.8788  ,   23.535063,  1.6062340e-01,   46.32384 , -3.2051343e-01, 0, 0, 0, 0.),
          ('10224-3702',  34.921377 , -2.5564066e-01, 195.6668  , 1.3862204 , -1.6729959e+01,  1.5509460e+01, 28.378273, 116.17908   , '1-35926', 10.16601842, 0.74650931,  7720.5   , 'AGBT20B_033_89',  896.6167 , 1.3215107 , -999., 0.02800583, 20.192286 , 3.8428867, 0.08978822, 10.039119,  7740.278 ,  3.4641643,  191.2422 ,  178.36139, 197.57574,  182.16835 , 183.52567 ,   11.018511 ,   23.338194,   17.698526,   68.30743 ,  5.7316750e-01,   59.911446, -5.1728141e-01, 0, 0, 0, 0.),
          ('10503-9102', 159.87381  ,  5.7953952e+00, 126.40233 , 2.3355197 , -4.4089720e+00,  6.6219531e+00, 30.179515,  87.34609   , '1-183743',  9.75156116, 0.47712874,  8348.503 , 'ALFALFA',   48.     , 2.        , -999., 0.00992001, 12.2      , 1.2      , 0.06      ,  9.64    ,  8354.    ,  4.       , -999.     , -999.     , 157.     , -999.      , 121.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('10515-12704', 148.03445  ,  4.2523171e+00, 138.94256 , 4.2670637 , -1.6450909e+00, -7.2061157e+00, 34.331714,  18.226318  , '1-78377',  9.80912685, 0.47087166,  8890.498 , 'ALFALFA',   48.     , 2.67      , -999., 0.01267325, 14.2      , 2.28     , 0.09      ,  9.97    ,  8890.    ,  3.5      , -999.     , -999.     , 255.     , -999.      , 179.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('10520-12704', 157.51996  ,  5.0475460e+00, 118.22678 , 2.5951877 ,  3.3335621e+00,  8.4892583e+00, 65.5289  ,   8.5068755 , '1-79664', 10.03257847, 0.8820504 , 10673.293 , 'ALFALFA',   48.     , 2.47      , -999., 0.00775519, 12.5      , 2.46     , 0.11      , 10.16    , 10692.    ,  8.       , -999.     , -999.     , 151.     , -999.      , 317.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('10844-3703', 146.39771  ,  4.4105842e+00,  32.393385, 1.0565393 ,  6.8336016e+00,  2.5680063e+00, 66.67108 , 347.40787   , '1-78176',  9.2939682 , 0.37352663,  5971.0635, 'ALFALFA',   48.     , 2.21      , -999., 0.01073654, 11.7      , 1.25     , 0.06      ,  9.38    ,  5971.    ,  1.5      , -999.     , -999.     , 218.     , -999.      , 116.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11004-12703', 195.87115  ,  2.6550518e+01, 114.53024 , 0.74770882,  4.7067644e-01,  3.9040249e+01, 57.37413 ,  37.871972  , '1-457076', 10.19424057, 0.83467799,  6625.625 , 'ALFALFA',   48.     , 2.15      , -999., 0.01076165, 21.5      , 3.99     , 0.1       , 10.      ,  6672.    ,  2.5      , -999.     , -999.     , 121.     , -999.      , 369.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11004-12705', 196.11763  ,  2.6671955e+01, 208.47741 , 2.5200443 ,  8.3291875e-01, -2.9800329e+00, 62.092323, 338.06773   , '1-457074', 10.34748459, 0.84010178, 10778.556 , 'ALFALFA',   48.     , 2.39      , -999., 0.00550453, 10.3      , 2.66     , 0.13      , 10.19    , 10768.    ,  4.5      , -999.     , -999.     , 114.     , -999.      , 485.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11009-12703', 195.77473  ,  2.6531116e+01,  71.265471, 1.1884043 , -6.1052090e+00,  1.1596333e+00, 55.797479,  84.86002   , '1-456645',  9.63690281, 0.75871021,  5735.5273, 'ALFALFA',   48.     , 2.06      , -999., 0.00715348, 12.9      , 1.98     , 0.08      ,  9.54    ,  5757.    , 10.       , -999.     , -999.     , 195.     , -999.      , 276.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11743-12705', 118.51873  ,  1.3954120e+01, 109.54253 , 3.4017927 ,  4.0763479e+00, -1.1129875e+01, 70.934723, 146.7655    , '1-604873', 10.11927986, 0.898206  ,  8876.227 , 'ALFALFA',   48.     , 2.35      , -999., 0.00801065, 12.1      , 2.02     , 0.09      ,  9.91    ,  8905.    , 17.5      , -999.     , -999.     , 120.     , -999.      , 252.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11828-3703', 163.26602  ,  4.6318672e+00,  66.962706, 1.5361722 ,  5.7903734e+00,  2.7273463e+01, 31.322661, 166.7808    , '1-587628',  9.73263741, 0.47118574,  5793.155 , 'ALFALFA',   48.     , 2.33      , -999., 0.01668081, 18.6      , 2.27     , 0.08      ,  9.62    ,  5805.    ,  7.5      , -999.     , -999.     , 355.     , -999.      , 135.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11945-6101', 251.04505  ,  3.9788762e+01, 154.11506 , 2.7145369 , -1.7094980e-03,  7.6127270e+00, 51.984137, 341.4728    , '1-95069', 10.26807939, 0.72809834,  9067.6   , 'AGBT20B_033_64',  897.2083 , 1.8771948 , -999., 0.03974172, 20.170805 , 7.2870145, 0.16182217, 10.455531,  9087.897 ,  9.52431  ,  314.1277 ,  267.38898, 325.32562,  274.41998 , 283.60028 ,   10.9648075,   33.118103,   23.446821,   66.14643 ,  3.3195257e-01,  120.60121 , -7.2269672e-01, 0, 0, 0, 0.),
          ('11960-12701', 236.53669  ,  8.7928795e+00, 150.44385 , 2.7708807 ,  4.4461226e+00,  2.0231778e+01, 60.458184, 110.09778   , '1-336461', 10.48429012, 0.81333238, 11544.772 , 'ALFALFA',   48.     , 2.44      , -999., 0.00825873, 14.4      , 3.       , 0.12      , 10.3     , 11589.    ,  4.       , -999.     , -999.     ,  86.     , -999.      , 362.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11974-3703', 238.81137  ,  1.0521325e+01, 150.50231 , 2.1011062 , -1.0133058e+00, -7.2647886e+00, 40.040463, 120.50242   , '1-633383', 10.28704834, 0.47464862, 12026.376 , 'ALFALFA',   48.     , 2.45      , -999., 0.00833   , 10.2      , 1.5      , 0.09      , 10.03    , 12012.    , 15.       , -999.     , -999.     , 191.     , -999.      , 180.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('11984-12701', 255.6625   ,  2.1576748e+01,  72.495624, 1.2836402 ,  6.7944712e+00, -8.0285697e-01, 55.737403, 347.34239   , '1-273427',  9.93251547, 0.89494702,  9360.6   , 'AGBT20B_033_75',  797.5712 , 1.7827653 , -999., 0.02348345, 12.172483 , 5.1471934, 0.15484983, 10.330397,  9364.834 ,  4.4023404,  319.04892,  309.19482, 324.99057,  309.90784 , 309.75137 ,    8.279177 ,   18.717413,   19.569536,   82.70928 ,  4.5184362e-01,  154.23734 , -8.8544476e-01, 0, 0, 0, 0.),
          ('12078-12705',  28.525879 ,  9.5060080e-01,  75.049348, 2.0775888 ,  4.4137291e+00, -6.5218012e+00, 47.515197, 341.56735   , '1-35251',  9.77759743, 0.53279769,  8237.411 , 'ALFALFA',   48.     , 3.04      , -999., 0.01540522, 11.5      , 1.59     , 0.1       ,  9.68    ,  8214.    , 26.5      , -999.     , -999.     , 182.     , -999.      , 103.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12084-12702', 344.89937  ,  1.4089555e+01, 107.26933 , 4.3056153 ,  1.5095482e+00,  3.1560519e+00, 66.261891, 330.87173   , '1-117088',  9.95206451, 0.89503592,  7706.418 , 'ALFALFA',   48.     , 2.46      , -999., 0.00847866, 13.7      , 2.68     , 0.11      ,  9.84    ,  7707.    ,  5.       , -999.     , -999.     ,  83.     , -999.      , 316.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12085-9102', 345.66796  ,  1.3329092e+01, 171.73582 , 1.8969716 ,  2.2696910e+00,  1.0159357e+01, 55.252506, 290.96795   , '1-116989', 10.48972416, 0.70684522,  8289.967 , 'ALFALFA',   48.     , 1.76      , -999., 0.007066  , 17.5      , 2.68     , 0.08      ,  9.91    ,  8305.    ,  1.5      , -999.     , -999.     , 129.     , -999.      , 380.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12089-12702', 351.92856  ,  1.4544752e+01, 144.56341 , 3.841654  ,  1.5268287e+00, -1.4401056e+01, 43.106119, 228.52735   , '1-117882', 10.124547  , 0.67718035,  9312.439 , 'ALFALFA',   48.     , 2.31      , -999., 0.00723055, 11.       , 1.79     , 0.09      ,  9.84    ,  9302.    ,  2.5      , -999.     , -999.     , 129.     , -999.      , 247.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12484-6102', 196.42096  ,  3.3178917e+01, 210.06975 , 1.2709755 ,  4.2734254e+00, -4.5731068e+00, 34.307222, 275.37456   , '1-402704', 10.6097784 , 0.37407729,  9723.023 , 'ALFALFA',   48.     , 2.59      , -999., 0.00845628, 14.1      , 3.15     , 0.12      , 10.18    ,  9745.    , 11.       , -999.     , -999.     , 277.     , -999.      , 373.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12506-12703', 219.46111  ,  5.0112384e+00,  92.178683, 2.2858251 ,  2.2677873e+00, -2.1941023e+01, 61.095875,   5.851015  , '1-630772',  9.57144165, 0.88850135,  7546.0415, 'ALFALFA',   48.     , 2.25      , -999., 0.00731194, 10.9      , 1.65     , 0.09      ,  9.68    ,  7549.    ,  1.5      , -999.     , -999.     , 219.     , -999.      , 225.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12518-6103', 157.40451  ,  9.5118751e-01, 109.46391 , 2.5079291 ,  1.6911174e+00, -1.0882724e+00, 62.840754, 260.21395   , '1-2604',  9.39098549, 0.82268447,  6747.8384, 'ALFALFA',   48.     , 2.76      , -999., 0.01077918, 14.       , 2.78     , 0.11      ,  9.83    ,  6739.    ,  1.5      , -999.     , -999.     , 243.     , -999.      , 257.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12518-9101', 159.23905  ,  2.2974766e-01, 149.44405 , 2.2742759 ,  5.6537534e+00, -5.0785764e-01, 47.698753,   3.689399  , '1-2742', 10.45972061, 0.64007777,  8761.486 , 'ALFALFA',   48.     , 3.01      , -999., 0.01040231, 15.3      , 4.09     , 0.15      , 10.21    ,  8767.    ,  2.5      , -999.     , -999.     , 314.     , -999.      , 392.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12620-6103', 200.06151  ,  3.0987795e+01, 120.76709 , 1.0841843 ,  4.4583478e+00,  1.5325043e+01, 51.470717, 313.73752   , '1-419023', 10.35906696, 0.70932531,  7179.084 , 'ALFALFA',   48.     , 2.07      , -999., 0.00765582, 16.1      , 2.9      , 0.1       ,  9.89    ,  7189.    ,  2.5      , -999.     , -999.     , 253.     , -999.      , 379.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12620-9101', 201.17742  ,  2.9049612e+01,  66.842333, 2.2985917 ,  6.2986002e+00,  2.7217926e+00, 56.018666, 353.87137   , '1-401502',  9.57260418, 0.67101616,  7047.155 , 'ALFALFA',   48.     , 1.73      , -999., 0.00704608, 14.6      , 1.82     , 0.07      ,  9.67    ,  7049.    , 10.5      , -999.     , -999.     , 538.     , -999.      , 257.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('12621-6103', 204.69116  ,  3.0480449e+01, 159.3745  , 2.1954219 ,  1.1779382e+00,  1.7178220e-01, 66.348562, 356.46981   , '1-415931',  9.90255165, 0.87040305,  7816.037 , 'ALFALFA',   48.     , 2.25      , -999., 0.00959225, 17.5      , 3.23     , 0.1       , 10.      ,  7822.    ,  2.       , -999.     , -999.     ,  98.     , -999.      , 337.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('7960-12704', 259.04431  ,  3.1792308e+01, 108.15231 , 3.194387  ,  1.8517326e+00,  2.7866365e-01, 65.502562, 153.79768   , '1-177542',  9.85870258, 0.90979866,  6856.2   , 'AGBT17A_012_94',  897.0116 , 1.4891174 , -999., 0.02095403, 13.07144  , 4.3052096, 0.12659664,  9.985682,  6872.0693, 12.5978775,  306.48547,  279.6875 , 331.28662,  288.927   , 297.07227 ,    8.725876 ,   17.461687,   12.719254,   62.049202,  3.4488675e-01,   28.613775, -1.4626110e-01, 0, 0, 0, 0.),
          ('7981-3703', 339.28214  ,  1.4231951e+01, 147.25706 , 1.931303  ,  4.9646976e+00,  5.0313138e-01, 61.927563, 211.71035   , '1-636441', 10.36083984, 0.8577702 , 11280.113 , 'ALFALFA',   48.     , 2.26      , -999., 0.00594202, 11.4      , 2.24     , 0.11      , 10.12    , 11363.    , 32.       , -999.     , -999.     , 108.     , -999.      , 376.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8080-6101',  47.787486 ,  2.3518094e-01, 115.32993 , 3.1012445 , -2.0979588e-01, -2.6830252e+01, 56.019058,  95.855544  , '1-37908',  9.53185429, 0.76290837,  7920.8   , 'AGBT17A_012_183',  620.7673 , 1.6741246 , -999., 0.02176832, 12.002808 , 3.4147406, 0.13072725, 10.006507,  7910.4204,  5.5183935,  265.4307 ,  249.8418 , 269.97424,  249.84268 , 252.83417 ,    8.244815 ,   18.140266,   18.13923 ,   62.190018,  4.0165752e-01,   74.39817 , -4.9277490e-01, 0, 0, 0, 0.),
          ('8089-6101',   6.4019834,  1.4115274e+01,  31.407507, 2.0403093 ,  2.2689459e+00, -6.9848648e+00, 84.145857, 211.43421   , '1-120697',  8.88122463, 0.61034912,  5254.31  , 'ALFALFA',   48.     , 2.38      , -999., 0.0265528 , 23.       , 2.28     , 0.07      ,  9.47    ,  5253.    ,  3.       , -999.     , -999.     , 119.     , -999.      ,  85.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8131-12701', 111.10794  ,  3.8945215e+01,  44.873675, 2.024364  ,  3.6772496e+00,  1.7964024e+01, 74.494996, 184.54342   , '1-584473',  9.23247515, 0.87271304,  5135.    , 'AGBT17A_012_02-AGBT17A_012_29',  388.6028 , 2.1900084 , -999., 0.02905285, 12.266089 , 4.5251164, 0.16531213,  9.756811,  5143.6836,  5.6544757,  233.3215 ,  220.8179 , 242.09976,  224.29549 , 226.39081 ,    8.434403 ,   19.027857,   24.210705,   69.23992 ,  5.0775951e-01,  125.06074 , -9.5347846e-01, 0, 0, 0, 0.),
          ('8137-12703', 116.16926  ,  4.4144409e+01, 182.43294 , 3.6065602 ,  9.1534770e-01,  1.4282612e+01, 52.127369, 162.76732   , '1-338796', 10.29858893, 0.6963261 , 11478.1   , 'AGBT17A_012_11-AGBT17A_012_13', 1155.6    , 1.4388001 , -999., 0.01586651, 11.0276   , 3.444    , 0.08800966, 10.332158, 11490.31  ,  6.09143  ,  340.356  ,  327.113  , 345.8843 ,  331.72638 , 332.6895  ,    7.2746787,   13.22    ,   11.37    ,   68.71    ,  3.6000001e-01,   71.75    , -3.8000000e-01, 0, 0, 0, 0.),
          ('8140-12704', 117.92377  ,  4.2303574e+01,  57.888471, 4.0997068 ,  7.9000338e-01, -1.3421116e+01, 69.070381, 294.63289   , '1-43651',  9.40031345, 0.74602178,  7211.4   , 'AGBT17A_012_69',  866.9    , 1.51572   , -999., 0.02083742, 13.7475   , 3.0240002, 0.07561281,  9.873961,  7212.2   ,  3.74879  ,  226.29831,  215.09773, 228.84702,  218.86707 , 217.49995 ,    8.581863 ,   17.36    ,   12.35    ,   53.81    ,  4.0000001e-01,   66.78    , -5.2999997e-01, 0, 0, 0, 0.),
          ('8145-6103', 116.50304  ,  2.8699634e+01,  34.998522, 1.317621  ,  6.9465605e+00, -1.8933133e+01, 55.213692,  73.800623  , '1-201291',  9.55081177, 0.51083928,  7086.435 , 'ALFALFA',   48.     , 2.27      , -999., 0.01124529, 13.2      , 1.6      , 0.07      ,  9.61    ,  7087.    ,  2.5      , -999.     , -999.     , 195.     , -999.      , 142.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8147-12703', 118.59263  ,  2.7008804e+01, 153.80479 , 4.0489567 ,  2.0301319e-01,  9.5742133e+00, 39.034698, 264.8025    , '1-146028', 10.03215504, 0.51635838,  7980.158 , 'ALFALFA',   48.     , 2.16      , -999., 0.01069472, 17.4      , 2.65     , 0.09      ,  9.93    ,  8013.    ,  4.       , -999.     , -999.     , 192.     , -999.      , 247.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8148-9101', 117.90207  ,  2.7379675e+01,  49.425498, 3.0426552 ,  5.4513739e+00, -9.3463704e+00, 67.113169, 196.10911   , '1-145806',  9.67757225, 0.78158945,  8036.5967, 'ALFALFA',   48.     , 2.15      , -999., 0.00805857, 12.       , 1.65     , 0.08      ,  9.73    ,  8013.    , 13.       , -999.     , -999.     , 293.     , -999.      , 205.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8148-9102', 117.9257   ,  2.7607393e+01, 110.75098 , 3.3355468 ,  5.4807869e-01,  7.0490480e+00, 40.653388, 139.78051   , '1-145802',  9.42992687, 0.68790323,  7934.172 , 'ALFALFA',   48.     , 1.98      , -999., 0.00670142, 11.7      , 1.61     , 0.08      ,  9.71    ,  7940.    ,  3.5      , -999.     , -999.     , 601.     , -999.      , 239.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8150-6101', 148.04613  ,  3.3450991e+01, 147.79215 , 2.3097152 , -5.1524136e+00, -1.8553841e+01, 58.005398, 145.22167   , '1-390151',  9.89253616, 0.58688217,  8109.094 , 'ALFALFA',   48.     , 1.86      , -999., 0.00560149, 10.9      , 1.47     , 0.08      ,  9.69    ,  8083.    ,  2.       , -999.     , -999.     ,  59.     , -999.      , 262.      , -999.       , -999.      , -999.      , -999.      , -9.9900000e+02, -999.      , -9.9900000e+02, 0, 0, 0, 0.),
          ('8314-12704', 243.70637  ,  3.9514366e+01, 130.28203 , 3.1328565 ,  2.0180498e+00,  3.6690263e+01, 63.759544, 132.25827   , '1-594358', 10.14898496, 0.88762788,  9683.    , 'AGBT17A_012_335',  836.22406, 1.6203421 , -999., 0.03212115, 18.823683 , 6.196919 , 0.14273039, 10.443829,  9726.989 ,  3.850838 ,  342.29736,  325.21213, 345.53058,  330.71527 , 329.57428 ,   10.577038 ,   21.712152,   26.767622,  108.55054 ,  5.6029099e-01,  173.64539 , -9.1665912e-01, 0, 0, 0, 0.),

In [15]:
data.columns

ColDefs(
    name = 'PLATEIFU'; format = '11A'
    name = 'RA'; format = 'D'
    name = 'DEC'; format = 'D'
    name = 'V_c'; format = 'D'
    name = 'R_t'; format = 'D'
    name = 's_out'; format = 'D'
    name = 'V_sys'; format = 'D'
    name = 'Incl'; format = 'D'
    name = 'Phi0'; format = 'D'
    name = 'MANGAID'; format = '9A'
    name = 'LOGMSTARS'; format = 'D'
    name = 'SINI'; format = 'D'
    name = 'VOPT'; format = 'E'
    name = 'SESSION'; format = '79A'
    name = 'EXP'; format = 'E'
    name = 'RMS'; format = 'E'
    name = 'LOGHILIM200KMS'; format = 'E'
    name = 'PEAK'; format = 'E'
    name = 'SNR'; format = 'E'
    name = 'FHI'; format = 'E'
    name = 'EFHI'; format = 'E'
    name = 'LOGMHI'; format = 'E'
    name = 'VHI'; format = 'E'
    name = 'EV'; format = 'E'
    name = 'WM50'; format = 'E'
    name = 'WP50'; format = 'E'
    name = 'WP20'; format = 'E'
    name = 'W2P50'; format = 'E'
    name = 'WF50'; format = 'E'
    name = 'DW'; format = 'E'
    name = 'PR'; format = 'E'
    name = 'PL'; format = 'E'
    name = 'AR'; format = 'E'
    name = 'BR'; format = 'E'
    name = 'AL'; format = 'E'
    name = 'BL'; format = 'E'
    name = 'NEGDET'; format = 'I'
    name = 'BLSTRUCT'; format = 'I'
    name = 'conflag'; format = 'I'
    name = 'conf_prob'; format = 'D'
)

In [22]:
data[0]

('10213-9101', 122.36352, 43.934918, 207.03249, 3.7470374, -3.6288854, -9.9420569, 64.449786, 161.11613, '1-44999', 9.918296182095766, 0.8263278165929279, 6884.2, 'AGBT17A_012_340', 846.18695, 1.7190437, -999.0, 0.019475918, 10.329507, 4.07699, 0.15571973, 9.96224, 6874.3486, 4.78287, 343.6021, 333.9316, 348.96988, 334.0506, 335.87897, 7.5238743, 16.22993, 16.028118, 109.80094, 0.5830097, 102.230255, -0.5404818, 0, 0, 0, 0.0)

In [24]:
import pandas as pd

In [121]:
df = pd.read_csv('forbidden.txt', delimiter=',')

In [122]:
df

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
0,('10213-9101',122.363520,43.934918,207.032490,3.747037,-3.628885,-9.942057,64.449786,161.116130,'1-44999',...,16.028118,109.800940,0.583010,102.230255,-0.540482,0,0,0,0.),
1,('10214-1902',121.988290,34.227327,26.348096,0.428787,4.497881,-2.914245,31.790592,276.262280,'1-153402',...,13.859993,40.737713,0.456845,20.681894,-0.188275,0,0,0,0.),NaN
2,('10214-6101',123.061820,35.157138,29.521736,0.996485,0.472039,-19.741566,49.908095,67.802374,'1-153412',...,16.878800,23.535063,0.160623,46.323840,-0.320513,0,0,0,0.),NaN
3,('10224-3702',34.921377,-0.255641,195.666800,1.386220,-16.729959,15.509460,28.378273,116.179080,'1-35926',...,17.698526,68.307430,0.573168,59.911446,-0.517281,0,0,0,0.),NaN
4,('10503-9102',159.873810,5.795395,126.402330,2.335520,-4.408972,6.621953,30.179515,87.346090,'1-183743',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,('9500-12702',132.598330,25.954082,169.264310,3.245579,1.494181,-1.606211,57.048775,116.806910,'1-605504',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
76,('9502-9102',129.030900,25.112727,120.809450,2.801706,0.184838,4.022161,70.295674,79.668840,'1-385129',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
77,('9504-3703',123.872820,29.821746,25.297445,0.807813,-0.796352,7.088298,62.359052,169.645910,'1-164405',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
78,('9506-9102',135.090250,27.980266,143.172170,3.883820,0.682183,-3.363937,73.781933,241.887950,'1-386298',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
79,('9882-12705',207.781130,24.018234,173.268400,2.637309,1.869593,-9.301805,57.776604,133.771940,'1-537118',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN

In [123]:
df.columns[1:4]

Index([' RA', ' DEC', ' V_c'], dtype='object')

In [124]:
df.iloc[1:4]

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
1,('10214-1902',121.988290,34.227327,26.348096,0.428787,4.497881,-2.914245,31.790592,276.262280,'1-153402',...,13.859993,40.737713,0.456845,20.681894,-0.188275,0,0,0,0.),NaN
2,('10214-6101',123.061820,35.157138,29.521736,0.996485,0.472039,-19.741566,49.908095,67.802374,'1-153412',...,16.878800,23.535063,0.160623,46.323840,-0.320513,0,0,0,0.),NaN
3,('10224-3702',34.921377,-0.255641,195.666800,1.386220,-16.729959,15.509460,28.378273,116.179080,'1-35926',...,17.698526,68.307430,0.573168,59.911446,-0.517281,0,0,0,0.),NaN

In [125]:
df[:5]

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
0,('10213-9101',122.363520,43.934918,207.032490,3.747037,-3.628885,-9.942057,64.449786,161.116130,'1-44999',...,16.028118,109.800940,0.583010,102.230255,-0.540482,0,0,0,0.),
1,('10214-1902',121.988290,34.227327,26.348096,0.428787,4.497881,-2.914245,31.790592,276.262280,'1-153402',...,13.859993,40.737713,0.456845,20.681894,-0.188275,0,0,0,0.),NaN
2,('10214-6101',123.061820,35.157138,29.521736,0.996485,0.472039,-19.741566,49.908095,67.802374,'1-153412',...,16.878800,23.535063,0.160623,46.323840,-0.320513,0,0,0,0.),NaN
3,('10224-3702',34.921377,-0.255641,195.666800,1.386220,-16.729959,15.509460,28.378273,116.179080,'1-35926',...,17.698526,68.307430,0.573168,59.911446,-0.517281,0,0,0,0.),NaN
4,('10503-9102',159.873810,5.795395,126.402330,2.335520,-4.408972,6.621953,30.179515,87.346090,'1-183743',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN

In [126]:
print(df.columns.tolist())

['PLATEIFU', ' RA', ' DEC', ' V_c', ' R_t', ' s_out', 'V_sys', ' Incl', ' Phi0', ' MANGAID', ' LOGMSTARS', ' SINI', ' VOPT', ' SESSION', ' EXP', ' RMS', ' LOGHILIM200KMS', ' PEAK', ' SNR', ' FHI', ' EFHI', ' LOGMHI', ' VHI', ' EV', ' WM50', ' WP50', ' WP20', ' W2P50', ' WF50', ' DW', ' PR', ' PL', ' AR', ' BR', ' AL', ' BL', ' NEGDET', ' BLSTRUCT', ' conflag', ' conf_prob', 'Unnamed: 40']

In [127]:
df['PLATEIFU']

0               ('10213-9101'
1               ('10214-1902'
2               ('10214-6101'
3               ('10224-3702'
4               ('10503-9102'
               ...
75              ('9500-12702'
76               ('9502-9102'
77               ('9504-3703'
78               ('9506-9102'
79              ('9882-12705'
Name: PLATEIFU, Length: 80, dtype: object

In [128]:
df[' RA']

0     122.363520
1     121.988290
2     123.061820
3      34.921377
4     159.873810
         ...
75    132.598330
76    129.030900
77    123.872820
78    135.090250
79    207.781130
Name:  RA, Length: 80, dtype: float64

In [129]:
df.loc[df[' Incl']>70]

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
11,('11743-12705',118.518730,13.954120,109.542530,3.401793,4.076348,-11.129875,70.934723,146.76550,'1-604873',...,-999.000000,-999.00000,-999.00000,-999.00000,-999.000000,0,0,0,0.),NaN
31,('8089-6101',6.401983,14.115274,31.407507,2.040309,2.268946,-6.984865,84.145857,211.43421,'1-120697',...,-999.000000,-999.00000,-999.00000,-999.00000,-999.000000,0,0,0,0.),NaN
32,('8131-12701',111.107940,38.945215,44.873675,2.024364,3.677250,17.964024,74.494996,184.54342,'1-584473',...,24.210705,69.23992,0.50776,125.06074,-0.953478,0,0,0,0.),NaN
76,('9502-9102',129.030900,25.112727,120.809450,2.801706,0.184838,4.022161,70.295674,79.66884,'1-385129',...,-999.000000,-999.00000,-999.00000,-999.00000,-999.000000,0,0,0,0.),NaN
78,('9506-9102',135.090250,27.980266,143.172170,3.883820,0.682183,-3.363937,73.781933,241.88795,'1-386298',...,-999.000000,-999.00000,-999.00000,-999.00000,-999.000000,0,0,0,0.),NaN

In [135]:
df.loc[df[' V_c']>150]

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
0,('10213-9101',122.363520,43.934918,207.03249,3.747037,-3.628885,-9.942057,64.449786,161.11613,'1-44999',...,16.028118,109.800940,0.583010,102.230255,-0.540482,0,0,0,0.),
3,('10224-3702',34.921377,-0.255641,195.66680,1.386220,-16.729959,15.509460,28.378273,116.17908,'1-35926',...,17.698526,68.307430,0.573168,59.911446,-0.517281,0,0,0,0.),NaN
9,('11004-12705',196.117630,26.671955,208.47741,2.520044,0.832919,-2.980033,62.092323,338.06773,'1-457074',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
13,('11945-6101',251.045050,39.788762,154.11506,2.714537,-0.001709,7.612727,51.984137,341.47280,'1-95069',...,23.446821,66.146430,0.331953,120.601210,-0.722697,0,0,0,0.),NaN
14,('11960-12701',236.536690,8.792879,150.44385,2.770881,4.446123,20.231778,60.458184,110.09778,'1-336461',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
15,('11974-3703',238.811370,10.521325,150.50231,2.101106,-1.013306,-7.264789,40.040463,120.50242,'1-633383',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
19,('12085-9102',345.667960,13.329092,171.73582,1.896972,2.269691,10.159357,55.252506,290.96795,'1-116989',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
21,('12484-6102',196.420960,33.178917,210.06975,1.270975,4.273425,-4.573107,34.307222,275.37456,'1-402704',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
27,('12621-6103',204.691160,30.480449,159.37450,2.195422,1.177938,0.171782,66.348562,356.46981,'1-415931',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
33,('8137-12703',116.169260,44.144409,182.43294,3.606560,0.915348,14.282612,52.127369,162.76732,'1-338796',...,11.370000,68.710000,0.360000,71.750000,-0.380000,0,0,0,0.),NaN
36,('8147-12703',118.592630,27.008804,153.80479,4.048957,0.203013,9.574213,39.034698,264.80250,'1-146028',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
48,('8482-3702',245.089660,49.943491,302.97634,1.870276,-6.474989,-1.931218,21.633471,102.83013,'1-542358',...,14.430000,14.810000,0.070000,32.790000,-0.180000,0,0,0,0.),NaN
53,('8713-6104',118.317320,39.050123,237.35778,1.533265,-4.141272,-3.675242,27.086534,191.41314,'1-43865',...,19.351885,29.383596,0.191860,42.502420,-0.273362,0,0,0,0.),NaN
58,('8983-12701',203.830210,26.424781,192.06040,2.381118,-0.509777,0.405298,56.612349,160.22108,'1-626658',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
62,('9040-6104',244.104430,27.246140,201.35650,1.733304,-0.831610,-11.816041,45.607972,192.79169,'1-296599',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
75,('9500-12702',132.598330,25.954082,169.26431,3.245579,1.494181,-1.606211,57.048775,116.80691,'1-605504',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
79,('9882-12705',207.781130,24.018234,173.26840,2.637309,1.869593,-9.301805,57.776604,133.77194,'1-537118',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN

In [136]:
df.loc[df[' V_c']<70]

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
1,('10214-1902',121.988290,34.227327,26.348096,0.428787,4.497881,-2.914245,31.790592,276.262280,'1-153402',...,13.859993,40.737713,0.456845,20.681894,-0.188275,0,0,0,0.),NaN
2,('10214-6101',123.061820,35.157138,29.521736,0.996485,0.472039,-19.741566,49.908095,67.802374,'1-153412',...,16.878800,23.535063,0.160623,46.323840,-0.320513,0,0,0,0.),NaN
7,('10844-3703',146.397710,4.410584,32.393385,1.056539,6.833602,2.568006,66.671080,347.407870,'1-78176',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
12,('11828-3703',163.266020,4.631867,66.962706,1.536172,5.790373,27.273463,31.322661,166.780800,'1-587628',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
26,('12620-9101',201.177420,29.049612,66.842333,2.298592,6.298600,2.721793,56.018666,353.871370,'1-401502',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
31,('8089-6101',6.401983,14.115274,31.407507,2.040309,2.268946,-6.984865,84.145857,211.434210,'1-120697',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
32,('8131-12701',111.107940,38.945215,44.873675,2.024364,3.677250,17.964024,74.494996,184.543420,'1-584473',...,24.210705,69.239920,0.507760,125.060740,-0.953478,0,0,0,0.),NaN
34,('8140-12704',117.923770,42.303574,57.888471,4.099707,0.790003,-13.421116,69.070381,294.632890,'1-43651',...,12.350000,53.810000,0.400000,66.780000,-0.530000,0,0,0,0.),NaN
35,('8145-6103',116.503040,28.699634,34.998522,1.317621,6.946560,-18.933133,55.213692,73.800623,'1-201291',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
37,('8148-9101',117.902070,27.379675,49.425498,3.042655,5.451374,-9.346370,67.113169,196.109110,'1-145806',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
41,('8329-12704',213.783650,45.594849,67.965915,2.235556,2.893149,-2.908234,65.005675,29.017850,'1-235203',...,21.960000,146.390000,1.080000,103.580000,-0.740000,0,0,0,0.),NaN
43,('8438-9101',148.052870,17.593560,49.951636,1.922673,6.479715,1.755035,57.372096,319.247750,'1-474540',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
46,('8448-12702',166.016630,22.635400,54.245006,2.333561,8.325135,100.444020,42.650834,249.507800,'1-486243',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
50,('8604-9102',246.455350,40.345209,68.360161,1.594347,4.043353,-16.948866,54.584415,95.572366,'1-210971',...,18.070000,10.800000,0.050000,13.120000,-0.080000,0,0,0,0.),NaN
51,('8616-9102',322.749440,-0.000594,57.357839,2.117399,3.577166,13.075069,57.377235,357.337100,'1-180135',...,15.604539,64.351150,0.469481,74.583300,-0.557892,0,0,0,0.),NaN
54,('8714-6101',118.716250,45.822555,14.380352,0.460713,0.763627,5.904853,34.222181,97.418968,'1-44210',...,26.867628,22.894846,0.384257,21.170416,-0.318997,0,0,0,0.),NaN
56,('8940-12701',119.708710,25.746257,37.207533,1.467599,2.727766,13.166944,66.589124,251.899430,'1-163887',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
57,('8982-9102',202.689200,26.521610,44.459748,2.315982,4.233587,-8.453275,62.744904,357.818850,'1-626395',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
61,('8992-12703',172.798560,51.698067,20.636968,1.925848,2.141163,-0.084553,66.467852,245.238200,'1-149887',...,18.352991,26.853172,0.305408,24.637560,-0.279186,0,0,0,0.),NaN
68,('9090-3704',243.141930,28.318974,31.011813,0.621328,3.759177,-5.146429,60.979129,239.885660,'1-633775',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
77,('9504-3703',123.872820,29.821746,25.297445,0.807813,-0.796352,7.088298,62.359052,169.645910,'1-164405',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN

In [141]:
hi_turnover_radii = df.loc[df[' R_t']>3.5] #where the turnover radius is larger than 3.5 arcseconds 
hi_turnover_radii

,PLATEIFU,RA,DEC,V_c,R_t,s_out,V_sys,Incl,Phi0,MANGAID,...,PL,AR,BR,AL,BL,NEGDET,BLSTRUCT,conflag,conf_prob,Unnamed: 40
0,('10213-9101',122.36352,43.934918,207.032490,3.747037,-3.628885,-9.942057,64.449786,161.116130,'1-44999',...,16.028118,109.800940,0.583010,102.230255,-0.540482,0,0,0,0.),
5,('10515-12704',148.03445,4.252317,138.942560,4.267064,-1.645091,-7.206116,34.331714,18.226318,'1-78377',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
18,('12084-12702',344.89937,14.089555,107.269330,4.305615,1.509548,3.156052,66.261891,330.871730,'1-117088',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
20,('12089-12702',351.92856,14.544752,144.563410,3.841654,1.526829,-14.401056,43.106119,228.527350,'1-117882',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
33,('8137-12703',116.16926,44.144409,182.432940,3.606560,0.915348,14.282612,52.127369,162.767320,'1-338796',...,11.370000,68.710000,0.360000,71.750000,-0.380000,0,0,0,0.),NaN
34,('8140-12704',117.92377,42.303574,57.888471,4.099707,0.790003,-13.421116,69.070381,294.632890,'1-43651',...,12.350000,53.810000,0.400000,66.780000,-0.530000,0,0,0,0.),NaN
36,('8147-12703',118.59263,27.008804,153.804790,4.048957,0.203013,9.574213,39.034698,264.802500,'1-146028',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
59,('8983-12705',203.91004,25.875237,113.513120,4.017350,4.644578,-14.752193,63.299035,150.126620,'1-626684',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
67,('9090-12704',243.90381,28.158585,139.370950,3.859290,3.107882,3.864005,42.890405,151.468760,'1-296849',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
69,('9093-12705',242.40634,28.051843,70.347382,3.728050,3.367708,5.891606,49.925004,80.882610,'1-594273',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN
72,('9493-12701',128.19586,22.576563,131.376120,4.767811,-3.472203,-6.029890,67.104506,168.896780,'1-384809',...,21.582298,31.283293,0.242461,35.007996,-0.222064,0,0,0,0.),NaN
73,('9494-9102',127.43484,22.424396,109.702930,3.596196,3.585564,17.965808,34.903390,300.809620,'1-384848',...,14.315136,31.287315,0.240053,42.172318,-0.326798,0,0,0,0.),NaN
78,('9506-9102',135.09025,27.980266,143.172170,3.883820,0.682183,-3.363937,73.781933,241.887950,'1-386298',...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0,0,0,0.),NaN